version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./backend/store:/data/db  # 호스트의 ./backend/store 디렉토리를 컨테이너의 /data/db로 마운트
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  store:
    driver: local
